trainer:
  class_path: maml_vmc.MamlTrainer.MamlTrainer
  init_args:
    reinit_layers: true
    seed: 5
    optimization_strategy: reptile
    eval_every: 1000000
    num_steps: 1801
    num_inner_steps: 200
    num_inner_steps_validation: 0
    num_systems: 1
    num_batches: 1
    num_systems_validation: 1
    store_every: 200
    reinit_ones: false
    model:
      class_path: maml_vmc.models.deep_erwin.DeepErwin.DeepErwin
      init_args:
        backflow_factor_net:
          n_max_electrons: 4
          n_dets: 32
        casscf_baseline:
          class_path: maml_vmc.models.deep_erwin.CASSCFBaseline.CASSCFBaseline
    optimizer: 
      class_path: maml_vmc.optimizer.AdamSchedule.AdamSchedule
      init_args:
        lr: 1.5e-3
    inner_optimizer: 
      class_path: maml_vmc.optimizer.Adam.Adam
      init_args:
        lr: 1.5e-3
    data_sampler:
      class_path: maml_vmc.sampler.MoleculeDataSampler.MoleculeDataSampler
      init_args:
        num_burnin_steps: 512
        num_inter_burnin_steps: 20
        num_steps: 1
        num_samples: 512
        step_size: 1
        dataset_path: exp/ds/train_h2_h4_chains/configs
        add_noise: true
    val_data_sampler:
      class_path: maml_vmc.sampler.MoleculeDataSampler.MoleculeDataSampler
      init_args:
        num_burnin_steps: 2048
        num_inter_burnin_steps: 20
        num_steps: 1
        num_samples: 2048
        step_size: 1
        dataset_path: exp/ds/train_h2_h4_chains
logger:
  class_path: maml_vmc.lijax.logger.WandbLogger.WandbLogger
  init_args:
    run_name: reptile_h2_h4_chains
    use_logger: true


